theme: minima
title: The Impact of the 2024 Election on Banking M&A
author: John Trettin
description: an in-depth analysis of "Trump Trades" and specifically its impact on the equity prices of financial institutions
